CREATE TABLE STUDENT (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	surname varchar(255) not null
);

CREATE SEQUENCE STUDENT_SEQ;
insert into STUDENT (name, surname) values ('Fodil', 'A');